### ISSUE TITLE
Replace HAN Font with roboto

### ISSUE THREAD

**Issue by meronbrouwer** [han-yaeger/yaeger#105]
https://fonts.google.com/specimen/Roboto#standard-styles

**Comment by sanmai-NL** [comment]
@meronbrouwer Why?

**Comment by meronbrouwer** [comment]
> @meronbrouwer Why?

Because there are some legal issues with including the HAN font.

**Comment by sanmai-NL** [comment]
@meronbrouwer For the sake of learning and documentation, and also to prevent busywork, can you elaborate?
