### ISSUE TITLE
Set Source target to JDK11

### ISSUE THREAD

**Issue by meronbrouwer** [han-yaeger/yaeger#114]
Yaeger should only target LTS versions of the JDK. Yaeger itself can use the latest&greatest, but the target audience should keep it simple and only use LTS versions

**Comment by meronbrouwer** [comment]
This might introduce more problems than solutions.

**Comment by sanmai-NL** [comment]
> **Oracle Java SE Product Releases**
Oracle provides Customers with Oracle Premier Support on Oracle Java SE products as described in the Oracle Lifetime Support Policy. For product releases after Java SE 8, Oracle will designate a release, every three years, as a Long-Term-Support (LTS) release. Java SE 11 is an LTS release. For the purposes of Oracle Premier Support, non‑LTS releases are considered a cumulative set of implementation enhancements of the most recent LTS release. Once a new feature release is made available, any previous non‑LTS release will be considered superseded. For example, Java SE 9 was a non‑LTS release and immediately superseded by Java SE 10 (also non‑LTS), Java SE 10 in turn is immediately superseded by Java SE 11. _Java SE 11 however is an LTS release, and therefore Oracle Customers will receive Oracle Premier Support and periodic update releases, even though Java SE 12 was released._
https://www.oracle.com/java/technologies/java-se-support-roadmap.html
**Conclusie**: alleen klanten van Oracle krijgen daadwerkelijk LTS.

OpenJDK neemt het verhaal over LTS over, maar concreet heeft LTS volgens mij weinig meerwaarde t.a.v. support.
> **WHAT DOES LTS MEAN WITH REGARDS TO JAVA / OPENJDK?**
> Long Term Support (LTS) in OpenJDK is really just an understanding between the various contributors (led by Oracle and Red Hat) that the code line for Java SE 11 / 17 / 23 etc will be maintained for a longer period of time than six months.
> Oracle will lead the first six months of an OpenJDK LTS code line, providing updates and producing Oracle OpenJDK builds, but will then afterward only provide updates for Oracle JDK, under a paid support plan.
https://medium.com/@javachampions/java-is-still-free-2-0-0-6b9aa8d6d244
**Conclusie**: alleen klanten van Oracle of een van hun partners krijgen daadwerkelijk LTS. Wel zou je bepaalde updates kunnen krijgen, door Red Hat, via OpenJDK.

**Comment by meronbrouwer** [comment]
Since only the source target will be set to JDK11, a big-bang rewrite will never be the case.

**Comment by sanmai-NL** [comment]
Ah that's true, you mean `maven.compiler.target`, not `maven.compiler.source`. You'll need to set `maven.compiler.release` as well then.
