### ISSUE TITLE
Create and deploy an MDBook as part of the workflow

### ISSUE THREAD

**Issue by meronbrouwer** [han-yaeger/yaeger#118]
On release we should create and deploy the documentation as a MDBook. 
An interesting feature would be to automatically check the Java code in the MD files to the just-build jar.

**Comment by sanmai-NL** [comment]
@meronbrouwer Which content would you like to include?

**Comment by meronbrouwer** [comment]
> @meronbrouwer Which content would you like to include?

The user documentation is still at an early stage, so it's not yet decided what should be included. This issue is currently just a reminder of the way the documentation can be deployed.

**Comment by sanmai-NL** [comment]
If you point me at some content that can be included experimentally, I can get started.

**Comment by meronbrouwer** [comment]
The docs/ folder contains a set of markdown files that will slowly become the user documentation. Creation of the MDbook should be be done as a gitHub Action for each release. Deployment could be either to the gh-pages of the yaeger repo, but this will mean it will have to be combined with the html of the JavaDoc. Another option is deployement to https://github.com/han-yaeger/
