### ISSUE TITLE
Windows concurrency bug

### ISSUE THREAD

**Issue by meronbrouwer** [han-yaeger/yaeger#121]
As reported by Jorg: Ik heb het werkend (IntelliJ en JDK 15). Als ik de showcase uitvoer, krijg ik bij het teruggaan van een scene naar het hoofdmenu een exception (ConcurrentModificationException).

**Comment by meronbrouwer** [comment]
This bug cannot be reproduced on MacOSX.

**Comment by sanmai-NL** [comment]
@meronbrouwer What has led you to believe it's related to the Java version?

**Comment by meronbrouwer** [comment]
> @meronbrouwer What has led you to believe it's related to the Java version?

Initially this bug was reported as a result of using JDK15, but since it couldn't reproduced on MacOSX with any JDK version, it seems related to Windows.

**Comment by sanmai-NL** [comment]
It could also be hard to reproduce in general ... But I was a bit skeptical Java versions differ in having simple concurrency defects.

**Comment by meronbrouwer** [comment]
@hahaje Since you're running Windows. Can you reproduce this bug?

**Comment by hahaje** [comment]
I was running the showcase with JDK14, changed it to JDK15. I did not encounter this concurrency problem
