### ISSUE TITLE
textEntity.getCenterY() en getTop() always returns 0

### ISSUE THREAD

**Issue by meronbrouwer** [han-yaeger/yaeger#137]
Reported by Abdel.

**Comment by AbdelHajou** [comment]
Update: So it turns out there was a misunderstanding because of the names of the methods. getCenterY, getCenterX etc return the positions of the bounds. In my opinion these methods should return the actual position of the entity, which is currently done by calling getAnchorLocation().getX().

**Comment by meronbrouwer** [comment]
Thanks for the analyses. I think I've stumbled upon a different manifestation of this bug, which causes a border crossing event, when the Entity is nowhere near the border of the Scene. I'm considering removing the getTop*, Bottom*, etc methods and only provide a getBounds(), which returns te boundingbox. That boundingbox can then provide get getTopX, etc.

The bug itself will still need to be resolved, but the API will change with the bugfix.

**Comment by meronbrouwer** [comment]
These methods have been removed in favour of getBoundingBox(), which returns the bounds. That object can then be used to get the leftX, rightX, centerX, etc
