### ISSUE TITLE
onMouseButtonPressed function parameters in the tutorial and code are not the same

### ISSUE THREAD

**Issue by TimMaasGeesteranus** [han-yaeger/yaeger#139]
The onMouseButtonPressed function has the parameters "double v, double v1". This does not correspond to the image in the tutorial, where the parameters are "double x, double y".

**Comment by AbdelHajou** [comment]
![image](https://user-images.githubusercontent.com/62144407/104856705-8b868900-5914-11eb-9171-3e51c6dbca75.png)
This has been fixed already, so this issue can be closed
