### ISSUE TITLE
Dynamic entities disappear when their speed is set to 0

### ISSUE THREAD

**Issue by AbdelHajou** [han-yaeger/yaeger#143]
Setting a Dynamic entity's speed to 0 and then applying motion again causes the entity to disappear. This can be reproduced by implementing KeyListener on a DynamicRectangleEntity:
```
    @Override
    public void onPressedKeysChange(Set<KeyCode> pressedKeys) {
        System.out.println(getAnchorLocation());
        if (pressedKeys.contains(KeyCode.LEFT)) {
            setMotion(3, Direction.LEFT.getValue());
        } else if (pressedKeys.isEmpty()) {
            setSpeed(0);
        }
    }
```

1. Press any button that is not LEFT
2. Press LEFT

Calling getAnchorLocation() returns: Point2D [x = NaN, y = NaN]

**Comment by meronbrouwer** [comment]
@AbdelHajou thanks! I'll look into this. Do you need this fixed asap?

**Comment by TimMaasGeesteranus** [comment]
I would like to have it fixed asap, the bug makes it impossible to build a big part of my game

**Comment by meronbrouwer** [comment]
@TimMaasGeesteranus ok, ik pak deze gelijk op.

**Comment by meronbrouwer** [comment]
b.t.w. @AbdelHajou Great bugpost, with a  great and  simple reproduction path.

**Comment by meronbrouwer** [comment]
@TimMaasGeesteranus  I resolved this bug. Hopefully you can continue with your game.
