### ISSUE TITLE
notifyBoundaryCrossing does not work  for dynamic entities on the right and bottom border 

### ISSUE THREAD

**Issue by TimMaasGeesteranus** [han-yaeger/yaeger#146]
This can be seen in the tutorial-implementation. 
Hanny can swim away from the screen, but only on the bottom and right side of the screen.

**Comment by meronbrouwer** [comment]
There was a problem with the boundingBox, which has been fixed. 

Issue #20 will introduce a way to visualise the bounding boxes, so that one might be interesting for debugging.
