### ISSUE TITLE
Provide a SpriteEntity constructor that uses the sprite's original dimensions

### ISSUE THREAD

**Issue by AbdelHajou** [han-yaeger/yaeger#158]
Sometimes it might be useful to use a sprite's original dimensions when using it in a game, because it can become tedious to ensure that the sprite's aspect ratio is maintained when providing the dimensions manually.

DynamicSpriteEntity only has constructors that require a Size argument, but it would be nice to have one without it that uses the sprite's dimensions by default.

**Comment by meronbrouwer** [comment]
I totally agree. Can you pick this one up? Besides the changes to the code, this one will need some good JavaDoc explaining the users which constructor they should use.

**Comment by meronbrouwer** [comment]
I've moved this one to the documentation lane to ensure we don't forget to implement it in the ShowCase.

**Comment by meronbrouwer** [comment]
@AbdelHajou will you implement this in the ShowCase, or should I do it?

**Comment by AbdelHajou** [comment]
@meronbrouwer I had already implemented this when I was testing it, by making the Swordfish use the new constructor. I'll open the PR tomorrow, I had some trouble with git today
