### ISSUE TITLE
Add an overloaded method for passing a third parameter to a Entity used in a TileMap

### ISSUE THREAD

**Issue by AbdelHajou** [han-yaeger/yaeger#159]
In the game I'm making I have three sprites for every type of tile (left corner, middle, and right corner). In order to instantiate these in a tile map, I have to make a new class for every different sprite. It would be a lot easier if I could specify parameters when adding tiles to the tilemap, for example:
```
public class Level1Map extends TileMap {
    @Override
    public void setupEntities() {
        addEntity(0, AirTile.class);
        addEntity(1, GroundTile.class, "sprites/tiles/grasstop_left.png");
        addEntity(2, GroundTile.class, "sprites/tiles/grasstop_middle.png");
    }
```

However, having games that look nice shouldn't be very important for learning purposes, so I guess this issue should have lower priority

**Comment by meronbrouwer** [comment]
Interesting feature. I imagine this not being too hard to implement. The main problem is dat this method is only available if the class extends a SpriteEntity (which can be easily done with generics)

**Comment by meronbrouwer** [comment]
We could add an overloaded addEntity() method with the following signature:

addEntity(int, YaegerEntity.class, K), 

where K is a generic parameter this is passed as a third constructor to the created Entity. 

* This approach will be type-safe and not involve any changes to the abstract entity classes. It will be up to the user to provide a constructor that accepts the correct type for the third parameter
* This approach is reusable, since it can be used for the url in spriteEntities, but it can also be used for passing a DTO that completely configures the Entity.

**Comment by AbdelHajou** [comment]
I've been looking into this, but the TileMap class has a hash map with every tile class and their indices. In order to add these generic parameters we would have to extend this hash map to also store those. Maybe I'm looking over something very obvious, but how could I store this generic parameter in the hash map (or another data structure)? First thing that comes to mind is something like this:
```
private final Map<Integer, Class<? extends YaegerEntity>> entities = new HashMap<>();
private final Map<Integer, C> entityConfigs = new HashMap<>();
```
Where C is the type that was passed as a parameter. However, this is impossible without adding the generic type to the TileMap class (TileMap<C>)

**Comment by meronbrouwer** [comment]
You're right. It's a bit more complex than I initially thought. The most important thing with solving this is that we want to have compile time type checks on the extra parameters. 
A second map could probably be made to work, but my gut feeling says its not the best solution. (gut feelings are sometimes wrong, though...)
I'll think about this some more. Feel free to propose a solution.

**Comment by meronbrouwer** [comment]
I've given it some more thought @AbdelHajou , and the best approach seems to provide an overloaded generic parameter to 
`addEntity(int, YaegerEntity.class, K)`

In the map, the value then needs to be changed to a DTO-type object that contains the class and the parameter. 
The method responsible for creating the actual entities will then need to check if the DTO contains a parameter and use this for the constructor of the Entity. 
This approach will leed to run-time errors, but those can be handled by an Exception with a clear explanation of what went wrong.

So, if you have the time and interest, give it a try. If not, I'll pick up in the near future.

**Comment by AbdelHajou** [comment]
@meronbrouwer Sounds like a good idea. Since the students don't learn about generics in their first year, I suppose nothing about that should be exposed in the API?

**Comment by meronbrouwer** [comment]
Nope, only an extra method with three parameters. Since the third can be anything, it's als possible to make it a dto,  which configures the entity.

**Comment by AbdelHajou** [comment]
@meronbrouwer I've implemented this, but I want to test it in an actual game instead of just unit tests. I'll open the PR tomorrow, for now you can see the commit at https://github.com/AbdelHajou/yaeger/commit/ea332a8d2e7f38fcc787b3e243bbdd077c760cc7

**Comment by meronbrouwer** [comment]
@AbdelHajou Looks promising. 

Could you also add several different usecases to the ShowCase project? This one will be used for example implementations, but also for manual e2e testing.

**Comment by AbdelHajou** [comment]
@meronbrouwer How shall I push these changes? It involves changes to two different repositories, and the code won't work on the showcase repo if the changes to the API aren't pulled as well.

**Comment by meronbrouwer** [comment]
If you create a pull-request on Yaeger, I'll review it. After I merged, we can update the showcase.
