### ISSUE TITLE
Ride the lightning showcase keeps throwing NullPointerExceptions

### ISSUE THREAD

**Issue by AbdelHajou** [han-yaeger/yaeger#164]
When running the Ride the lightning showcase using the latest development version of yaeger - which isn't on the showcase repo yet - NullPointerExceptions are constantly being thrown on line 251 of EntityCollection:

`boundingBoxVisualizers.removeAll(garbage);`

I think this has something to do with the changes that were recently made to the way bounding boxes are handled

**Comment by meronbrouwer** [comment]
Stupid me...
