### ISSUE TITLE
Implement Java Records for all data classes

### ISSUE THREAD

**Issue by meronbrouwer** [han-yaeger/yaeger#168]
In one of the coming jdk releases Records will be introduced, which can be used for all data classes.

**Comment by AbdelHajou** [comment]
I just looked into them a bit more, and it seems like records are always immutable and there's no option to make them mutable. I think this might be an issue for some of the data classes in Yaeger

**Comment by meronbrouwer** [comment]
At which places do expect problems to arise?

I guess that are some places where the code needs some changes to use the dataclasses as immutable objects, but that will only improve the code.

**Comment by AbdelHajou** [comment]
I'm not sure if you'd want to expose records through the API (like Coordinate2D, Size etc.) because the goal is to use object orientation

**Comment by meronbrouwer** [comment]
Records won't break the OO paradigm, but you'r right that we should be careful with them. I guess we can only expose them if OOPD add them to the course (which I don't think will happen).
Lombok would then be a good alternative to lessen the boilerplate code.

So this task can be closed. I'll create a new issue for introducing Lombok.
