### ISSUE TITLE
Add custom fonts to the showcase and manual

### ISSUE THREAD

**Issue by SimonVreman** [han-yaeger/yaeger#179]
Currently it's not completely obvious as to how someone would add a custom font (e.g. a .ttf file) to their project, or if it's even 'cleanly' possible. This is why it should be added to the manual and highlighted in the showcase to make sure fonts can easily and properly be implemented.

**Comment by meronbrouwer** [comment]
@SimonVreman I guess you have implemented custom fonts in you game, maybe I can use that implementation in the ShowCase. Could you point me to your code?

**Comment by SimonVreman** [comment]
It's in my private repository, I sent an invite. 
[This is my font class](https://github.com/SimonVreman/mariorooms_remastered/blob/main/src/main/java/com/github/simonvreman/mariorooms_remastered/styles/PixelFont.java)
[In this class I use the font](https://github.com/SimonVreman/mariorooms_remastered/blob/main/src/main/java/com/github/simonvreman/mariorooms_remastered/buttons/LongButton.java)
