### ISSUE TITLE
Create a webapplication that can be used to generate a new project

### ISSUE THREAD

**Issue by meronbrouwer** [han-yaeger/yaeger#183]
Since our students have no experience with Maven, we should provide an easy way to create a new project. We could provide a webapplication (hosted through gh-pages), that can be used to generate an empty project. 

This would be similar to Spring Boot Initializer (https://start.spring.io/). After setting the name of the game and the version of yaeger, the webapp should generate a Maven project, that can be downloaded as a zip-file, which can then be extracted and imported in the IDE.

Note that this should be a webapplication that can be statically hosted on GitHub pages and that does not need a server-side part. Preferable technologies are react, angular or flutter. Although this might also be a good usecase for a javafx application that is compiled for the browser.

**Comment by WiebeVanAken** [comment]
Hmm, this does sound interesting I've been looking for a small project to work on during the fall break.
I'll have finished the yaeger game for OOPD by the end of this week (ITA-1M, MBO Propedeuse). 
Perhaps I'll pick this up.

**Comment by meronbrouwer** [comment]
If you're thinking about picking this one up, we should talk about the requirements. I'll put some more info into this taks, since I already have a semi-clear picture of how this should be done.

**Comment by meronbrouwer** [comment]
This issue can be removed, as we're going to make a short instruction video that explains the process
