### ISSUE TITLE
[Bug] Window size given includes window decoration, actual canvas size is smaller.

### ISSUE THREAD

**Issue by SimonVreman** [han-yaeger/yaeger#185]
In the latest version of the engine, the application window size set by the game includes window decoration, messing up things like center alignment. Potentially related to issue #103. This also effects the showcase and tutorial projects.

An example of the current situation, with size set at 1600*900 in the root class extending `YaegerGame`. Notice how the last set of dots isn't properly on screen.
![loc@1600x900](https://user-images.githubusercontent.com/35310171/118375473-2856eb80-b5c2-11eb-9f22-5d3309a9eb73.png)

This is what the expected behavior would be. Notice how the last set of dots is perfectly visible on screen.
![fixloc@1600x900](https://user-images.githubusercontent.com/35310171/118375493-44f32380-b5c2-11eb-9f08-851a07ed04cb.png)

The cause of this bug is found in the `YaegerStage` class, specifically the `init()` function. Below is the current situation.
```java
public void init(final Injector injector) {
        stage.setResizable(false);
        sceneCollection = sceneCollectionFactory.create(stage, yaegerConfig);
        injector.injectMembers(sceneCollection);
        sceneCollection.init(injector);

        yaegerGame.setupGame();
        stage.setWidth(size.getWidth());
        stage.setHeight(size.getHeight());

        yaegerGame.setupScenes();
        sceneCollection.postSetupScenes();

        stage.show();
}
```

You can see the the functions `setWidth()` and `setHeight()` being used to set the size. However, according to JavaFX documentation these functions, inherited from the `Window` class, set the size including window decoration (for example the bar at the top containing the minimize, maximize and close buttons). A potential fix for this working in my specific, **_only tested in my own game_**, would be as below.
```java
public void init(final Injector injector) {
        stage.setResizable(false);
        sceneCollection = sceneCollectionFactory.create(stage, yaegerConfig);
        injector.injectMembers(sceneCollection);
        sceneCollection.init(injector);

        yaegerGame.setupGame();

        Scene scene = new Scene(new Group(), size.getWidth(), size.getHeight());
        stage.setScene(scene);
        stage.show();

        stage.setWidth(stage.getWidth());
        stage.setHeight(stage.getHeight());

        yaegerGame.setupScenes();
        sceneCollection.postSetupScenes();
        
        stage.show();
}
```
What this does is it creates a scene with the size we want, and just sets the size of `stage` to that size, which now includes the window decoration. There probably is a better way to implement a fix, however I am not familiar enough with the engine's code.

Hope this clearly shows the bug and a potential fix ;)

**Comment by SimonVreman** [comment]
I just noticed that this also affects the `getWidth()` and `getHeight()` methods on static and dynamic scenes, causing them to be inaccurate as they still include window decoration. A solution for this would be to make sure YaegerScenes return scene width not stage width. 

Current situation is as below, notice the stage width is being returned.

```
default double getWidth() {
    getStage();

    return getStage().getWidth();
}
```

To make sure the returned width does not include window decoration, you can just get the scene width. Below works flawlessly for my game.

```
default double getWidth() {
    return getStage().getScene().getWidth();
}
```

**Comment by meronbrouwer** [comment]
Great work @SimonVreman . This discusses a possible solution for a bug that has been in Yaeger since the beginning. If you want, you can try to solve it and create a pull-request. Otherwise I'll pick this up in the coming weeks.

**Comment by SimonVreman** [comment]
@meronbrouwer I created a pull request for the development branch. I can't seem to connect it to this issue, but the pull request number is #189. I've implemented the changes to `YaegerStage` as mentioned in the main post, and the changes to `YaegerScene` as mentioned in a later comment on this issue.

**Comment by meronbrouwer** [comment]
@SimonVreman  I have merged you fix into the development branch.

The main addition is the use of a factory for creating the Scene. In your code, the empty Scene was created by the YaegerStage, which introduced a tight coupling. When (unit)testing the YaegerStage, the consequence was that it created a Scene, which caused problems because the Scene expected to be created on a JavaFX-thread. 
To loosen the coupling, the creation of such objects is handled by a Factory (https://refactoring.guru/design-patterns/factory-method), which itself gets injected (https://www.baeldung.com/guice) into the YaegerStage. From our unittest we can than inject our special version of the SceneFactory, which creates a fake Scene, that does not require je JavaFX-Thread.

Thanks for the work!
