### ISSUE TITLE
[Bug] Tilemaps appear in front of regular scene entities

### ISSUE THREAD

**Issue by SimonVreman** [han-yaeger/yaeger#190]
Entities appear nicely in the order you add them to the scene, but the tilemaps appear on top. This relates to #178 but tilemaps should definitely not appear in front of the regular entities by default either way.

How it currently appears.
<img width=700 src="https://user-images.githubusercontent.com/35310171/119390706-b96a4880-bccd-11eb-80d3-0edf46f42f51.png">

How it should appear.
<img width=700 src="https://user-images.githubusercontent.com/35310171/119390768-cb4beb80-bccd-11eb-80a8-b25d54e03e9e.png">

This is how I fixed it for my specific case. I created an interface that moves entities to the back of the scene when added.
```java
public interface AlignBack {

    @OnActivation
    default void toBack() {
        this.getNode().ifPresent(Node::toBack);
    }

    Optional<? extends Node> getNode();
}
```

Then I proceeded to implement this interface in all my tile classes. Note that this also flips the order in which tilemaps appear when layered, so the foreground tilemap must be added first now which is counter intuitive.

**Comment by meronbrouwer** [comment]
Great solution, but most users might not be so capable. By default Tilemaps should be placed at the back. But we should also provide an API that makes it possible to add a z-index to an Entity.
