### ISSUE TITLE
[Enhancement] Add a MouseEnteredWhileDragged or have MouseEntered be called while dragging

### ISSUE THREAD

**Issue by SimonVreman** [han-yaeger/yaeger#193]
Currently you can't detect when a user enters or exits a `YaegerEntity` while dragging the mouse. This could be solved by creating an event like `MouseEntered` or `MouseExited`, which would be preferred, but could also be solved by adding the functionality to the existing enter and exit events. This can be used to enhance dragging and dropping, like highlighting a spot where you can drop something when you hover the entity being dragged over it.

Edit:
This also goes for `MouseMoved`, which isn't called when the mouse is dragged along.

On the technical side of things, I don't think there is an event in JavaFX that does _exactly_ this, but I managed to implement it by starting full drag on the scene's pane. This might however interfere with the new drag and drop functionality.

My implementation of the first suggested solution:
```java
public interface MouseEnterWhileDragListener extends GameNode {

    void onMouseEnteredWhileDrag();

    @OnActivation
    default void attachMouseEnteredWhileDragListener() {
        if (this instanceof YaegerEntity) {
            getNode().ifPresent(node -> node.getParent().setOnDragDetected(event -> node.getParent().startFullDrag()));
            getNode().ifPresent(node -> node.setOnMouseDragEntered(event -> onMouseEnteredWhileDrag()));
        }
    }
}
```

**Comment by meronbrouwer** [comment]
@SimonVreman We do have a MouseDragEnter and MouseDragExit. Can't they be used?

**Comment by SimonVreman** [comment]
These are called when you start dragging or stop dragging on an entity, so literally when you enter the drag, not the entity.

**Comment by meronbrouwer** [comment]
@SimonVreman Regarding the MouseDragEnter and MouseDragExit. These two behave as you requested. You can see them in action in the ShowCase. The get called when an entity that implements MouseDraggedListener gets dragged and enters or exits the Entity that implements either MouseDragEnter or MouseDragExit. 
Did you have a look at this and can you confirm my statement?

regarding the MouseMovedWhileDragging. I agree that we need this one and will try to integrate your solution. Main thing is that it shouldn't break the existing drag&drop system

**Comment by SimonVreman** [comment]
My bad, the actual behavior isn't as I described. However they don't get called when you're simply dragging the cursor without an Entity being dragged, which is where my confusion came from. So yes your statement is correct, but that also means there's no way to detect a mouse entering an Entity while being dragged, without an Entity implementing MouseDraggedListener being dragged.

**Comment by meronbrouwer** [comment]
Ok, the situation where you cannot detect a dragging mouse without something being dragged is acceptable for now. If this pops up as a serious problem, we can always put more effort into it.
