### ISSUE TITLE
Game dimensions do not seem to match window width and height on Windows 10

### ISSUE THREAD

**Issue by thomasreuvers** [han-yaeger/yaeger#208]
When running YAEGER on Windows 10 the Game dimensions don't seem to match the given window width and height. This is fixable by reshowing the stage in the `PostActivate()` function. This does update the scene (game dimension) size.

**Comment by meronbrouwer** [comment]
I have pushed the fix to the master-branch. Could you test if it works? Note that the version of Yaeger is 2021.2022.1-SNAPSHOT
