### ISSUE TITLE
IndexOutOfBoundException on start project

### ISSUE THREAD

**Issue by cedricfortuin** [han-yaeger/yaeger#254]
### What is the problem
When reopening and starting an already excisting project, the build results into the following error:

`
Module '[Project]' production: java.lang.IndexOutOfBoundsException: Range [-1, -1 + 1025) out of bounds for length 1024
`
Where `[Project]` the name of the project is.

When testing this on another project, it resulted in the same error.

### How to recreate the error
I think this error is quite specific.
I did the following things:
1. Create a project and develop a game
2. Close the IDE (at this point the game still runs)
3. Start the IDE again and try to run it: it gives the IndexOutOfBoundsException error

**Comment by cedricfortuin** [comment]
After further investigation and testing with a whole new project, I discovered that the error already excists when I start an entirely new project without changing any code or scaffolding. Will investigate further.

**Comment by meronbrouwer** [comment]
Looking at the error, it seems this is caused by the IDE and not Yaeger itself. What IDE and IDE-version are you using? Is there a stacktrace available?
