### ISSUE TITLE
Bug: getSpeedInDirection with same direction returns 0 instead of actual speed.

### ISSUE THREAD

**Issue by Liam-Rougoor** [han-yaeger/yaeger#265]
Imagine this line of code:
`setMotion(3, Direction.RIGHT);`

Now, `getSpeedInDirection(Direction.RIGHT)` returns 0, where I would expect 3.

This happens due to a comparison of the directions. When the directions are the same, the calculation is not performed and 0 is returned. I think this comparison should be removed.

**Comment by meronbrouwer** [comment]
Thanks for the bug-report and the Pull-request. I'll look into both and let you know when I merge your work.

**Comment by meronbrouwer** [comment]
Thanks @Liam-Rougoor
