### ISSUE TITLE
Throw Exceptions when a method is called that cannot complete its task

### ISSUE THREAD

**Issue by meronbrouwer** [han-yaeger/yaeger#49]
Because GameObjects are fully constructed when a Scene is started, some Dependencies will not be available when the constructor of the GameObject is called.

In such cases, we should throw a Exception to make this explicit.

Objects where this happens:
- SceneChild

**Comment by sanmai-NL** [comment]
@meronbrouwer Is `GameObject` the old name of `GameNode`?

**Comment by meronbrouwer** [comment]
This task is no longer relevant, since the architecture has changed since it was conceived
